'use client'

import './globals.css'
// import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useState, useEffect } from 'react'
import Footer from './components/Footer'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  const [theme, setTheme] = useState(() => {
    let savedDarkMode: string | null = null
    if (typeof window !== 'undefined') {
      savedDarkMode = localStorage.getItem('theme')
    }
    return savedDarkMode === 'dark' ? 'dark' : 'light'
  })

  useEffect(() => {
    if (window.matchMedia('prefers-color-scheme: dark').matches) {
      setTheme('dark')
    }
  }, [])

  useEffect(() => {
    localStorage.setItem('theme', JSON.stringify(theme))
    document.body.classList.toggle('dark', theme === 'dark')
  }, [theme])
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark:bg-gray-900 dark:text-white flex w-full h-full relative min-h-screen flex-col p-0 m-0 pb-14`}
      >
        <Header setTheme={setTheme} />
        {children}
        <Footer />
      </body>
    </html>
  )
}
